import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins font
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/shadcn/ui/tooltip";
import AuthImage  from '../../../public/assets/kf-auth.svg'
import Image from "next/image";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"], // Define the font weights you want to use
  subsets: ["latin"], // You can add more subsets if needed
  variable: "--font-poppins", // Use a CSS variable for easier reference
});
export const metadata: Metadata = {
  title: "Keshflip Pay - Client",
  description: "Generated by Redwan Null",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
            <div className="grid min-h-svh lg:grid-cols-2">
                    {children}
                    <div className="relative hidden  lg:block p-8 ">
                        <div className="w-full h-full flex flex-col items-center justify-between">
                            <Image src={AuthImage} alt="expImage"  width={700} height={600}/>
                        </div>
                    </div>
                </div>
    </main>
  );
}
