import type { Metadata } from "next";
import { SidebarInset, SidebarProvider } from "@/components/shadcn/ui/sidebar";
import { Toaster } from "@/components/shadcn/ui/sonner";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/header";


export const metadata: Metadata = {
  title: "Easy Ramp",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        <SidebarProvider>
        <Toaster position='top-center'/>
            <AppSidebar />
            <SidebarInset>
            <Header />
                <main className="px-4">
                    {children}
                </main>

            </SidebarInset>
        </SidebarProvider>
    </div>
  );
}
