import Navbar from "@/components/menu/navbar";
import { Separator } from "@/components/shadcn/ui/separator";
import type { Metadata } from "next";

// import TeamSwitcher from "./overview/components/team-switcher";
// import { MainNav } from "./overview/components/main-nav";
// import { Search } from "./overview/components/search";
// import { UserNav } from "./overview/components/user-nav";


export const metadata: Metadata = {
  title: "Easy Ramp",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
        {/* <div className="flex h-16 items-center px-4">
          <TeamSwitcher />
          <MainNav className="mx-6" />
          <div className="ml-auto flex items-center space-x-4">
            <Search />
            <UserNav />
          </div>
        </div> */}

        <div className="lg:w-8/12 lg:mx-auto py-3">
          <Navbar />
        </div>
        <Separator />
        <main className="py-4 lg:w-8/12 lg:mx-auto ">
            {children}
        </main>
    </div>
  );
}
