import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import { SidebarInset, SidebarProvider } from "@/components/shadcn/ui/sidebar";
import { Toaster } from "@/components/shadcn/ui/sonner";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/header";

// Load Poppins font with specified weights
const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"], // Define the font weights you want to use
  subsets: ["latin"], // You can add more subsets if needed
  variable: "--font-poppins", // Use a CSS variable for easier reference
});

export const metadata: Metadata = {
  title: "Easy Ramp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
             <SidebarProvider>
                <Toaster position='top-center'/>
                  <AppSidebar />
                  <SidebarInset>
                    <Header />
                      <main className="px-4">
                          {children}
                      </main>

                  </SidebarInset>
              </SidebarProvider>

      </body>
    </html>
  );
}
