import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google"; // Import Poppins font
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/shadcn/ui/tooltip";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700", "800", "900"], // Define the font weights you want to use
  subsets: ["latin"], // You can add more subsets if needed
  variable: "--font-poppins", // Use a CSS variable for easier reference
});
export const metadata: Metadata = {
  title: "Keshflip Pay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
            <TooltipProvider>
                <Toaster position="bottom-center" richColors/>
                <main>
                  {children}
                </main>
            </TooltipProvider>
      </body>
    </html>
  );
}
